Address rounding issue in Pandas series to floor numerically unstable values
usds/justice40-tool pull request #1085
Opened 2021-12-22 18:45 UTC by saran-ahluwalia

Addresses #1053. 

Includes utility function for flooring series and unit tests.

Thank you to @esfoobar-usds for assisting with updating tile data unit tests.

2021-12-28 19:24 UTC, vim-usds reviewed
Some basic questions

2021-12-29 14:26 UTC, saran-ahluwalia commented on data/data-pipeline/data_pipeline/etl/score/constants.py
> -    field_names.LOW_HS_EDUCATION_FIELD,
At the time, @lucasmbrown-usds had mentioned that these were extraneous and no longer pertinent. I defer to @lucasmbrown-usds for confirmation.

2021-12-29 14:27 UTC, saran-ahluwalia commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +    # we perform many operations using the division operator
Thanks

2021-12-30 01:11 UTC, lucasmbrown-usds requested changes
Overall looks fantastic!

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/constants.py
> -    field_names.LOW_HS_EDUCATION_FIELD,
I think perhaps at the time I was working on this branch with Saran, these fields were not actually created. Now due to this PR https://github.com/usds/justice40-tool/pull/1046 they are created, so we should no longer remove them from this constant. 

@saran-ahluwalia do you mind reverting this change to keep the code as it was in this file?

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +        series (pd.Series): Input pandas series
Upgrading our docstrings a bit, I love it!

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +    Floors all non-null numerical values to a specific number of decimal points
Nit: can we move the summary to the first line, like `"""Floors all non-null numerical...`? 

See for reference https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +    # Hence, to handle such offending values we default to None
👍 agreed, helpful comments!

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +        A Pandas Series
This is super nitty, but you could write: 

```
Returns: 
    floored_series (pd.Series): [a description]
```

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +    if series.empty:
love it!

2021-12-30 01:11 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/tests/test_etl_utils.py
> +def test_floor_series():
I really love how comprehensive these tests are!

2021-12-30 21:29 UTC, lucasmbrown-usds approved these changes
LGTM!

2021-12-30 21:29 UTC, lucasmbrown-usds commented on data/data-pipeline/data_pipeline/etl/score/etl_utils.py
> +        floored_series (pd.Series): A Pandas Series of numerical values with appropriate number of decimal points
🎉

2022-01-05 22:03 UTC, merged