Document current dependabot issues in config file
usds/justice40-tool pull request #1122
Opened 2022-01-11 17:03 UTC by sverchdotgov

Fixes: https://github.com/usds/justice40-tool/issues/1121

It's unclear whether this file is doing what we want it to do. This is an open issue in the dependabot repo. Added a comment to document the current status of what's going on here.

If these keep coming up (which they probably will), we might either want to disable dependabot or document a quick workflow for verifying this is a dev only issue (https://github.com/usds/justice40-tool/issues/1121 might be that documentation).

2022-01-12 14:15 UTC, esfoobar-usds requested changes
This is probably a left over from the previous iteration of the platform. I would just remote this file

2022-01-12 15:19 UTC, sverchdotgov commented
@esfoobar-usds Actually I added this file from the dependabot docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

I just think there's an open issue where it doesn't support the options we want right now (see https://github.com/dependabot/dependabot-core/issues/2521).

We could remove it, but it seems like the most logical place to capture that context.

2022-01-12 17:23 UTC, esfoobar-usds commented
Got it. I just don't understand the context. Sine the repo is both Python and Javascript, isn't this flagging the repo as JavaScript only?

2022-01-13 15:50 UTC, sverchdotgov commented
@esfoobar-usds Actually we now have an example showing that this isn't affecting how dependabot checks python: https://github.com/usds/justice40-tool/security/dependabot/data/data-pipeline/poetry.lock/Pillow/open

So I think either this config doesn't work as the documentation says, or configuring javascript behavior leaves the python behavior alone. Either way, this seems like it won't affect python dependency checks.

2022-01-13 16:41 UTC, esfoobar-usds commented
Closing pending further research

2022-01-13 16:41 UTC, closed without merging