Cleaning up quick code
usds/justice40-tool pull request #1349
Opened 2022-03-01 00:11 UTC by emma-nechamkin

Taking a minute to clean up / resubmit for review some of the quick and dirty changes from launch.

2022-03-01 00:12 UTC, emma-nechamkin commented on data/data-pipeline/data_pipeline/etl/score/etl_score.py
> +                df.where(df[field_names.AGRICULTURAL_VALUE_BOOL_FIELD] == True)[
this should be much cleaner. asserted that it was equal to the existing code.

2022-03-01 00:12 UTC, emma-nechamkin commented on data/data-pipeline/data_pipeline/score/score_m.py
> +            climate_eligibility_columns,
this should get rid of the bad code smell!

2022-03-01 00:14 UTC, emma-nechamkin commented on data/data-pipeline/data_pipeline/etl/score/etl_score.py
> +                df.where(df[field_names.AGRICULTURAL_VALUE_BOOL_FIELD] == True)[
`== True` is gross but the bool has `NaN`s that we need to keep, so it's necessary unfortunately.

2022-03-01 15:07 UTC, emma-nechamkin commented on data/data-pipeline/pyproject.toml
> +nb-black = "^1.0.7"
added this from the command line (`$ poetry add -D nb_black`)

2022-03-02 19:20 UTC, esfoobar-usds requested changes
PR is not passing.

You can patch this commit or make these one line change: https://github.com/usds/justice40-tool/pull/1252/commits/64d614bca00eb3989dc764e75abedf7662dc1e11

2022-03-02 20:40 UTC, esfoobar-usds approved these changes
🍏

2022-03-02 21:50 UTC, merged